# Macro file for visualization settings in initialization phase

# Create an OpenGL view
/vis/open OGL 600x600-0+0

# Disable auto refresh
/vis/viewer/set/autoRefresh false

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0

# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style w
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID id
/vis/modeling/trajectories/id/default/setDrawStepPts true
/vis/modeling/trajectories/id/default/setStepPtsSize 2

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

# Axes, scale, etc.
/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo
/vis/scene/add/logo    # 3D logo

# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)

# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false


# Make the particle scorers

/score/create/boxMesh first
/score/mesh/boxSize 60 60 4 cm
/score/mesh/translate/xyz 0 0 -60 cm
/score/mesh/nBin 40 40 2
/score/quantity/energyDeposit energy
/score/close

/score/create/boxMesh second
/score/mesh/boxSize 60 60 4 cm
/score/mesh/translate/xyz 0 0 0 cm
/score/mesh/nBin 40 40 2
/score/quantity/energyDeposit energy
/score/close

/score/create/boxMesh third
/score/mesh/boxSize 60 60 4 cm
/score/mesh/translate/xyz 0 0 60 cm
/score/mesh/nBin 40 40 2
/score/quantity/energyDeposit energy
/score/close

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

