# Macro file for visualization settings in initialization phase

# Create an OpenGL view
/vis/open OGL 600x600-0+0

# Disable auto refresh
/vis/viewer/set/autoRefresh false

# Draw geometry:
/vis/drawVolume

# Sets all volumes as solids, and colors them accordingly
/vis/viewer/set/style s
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/geometry/set/colour ej309 1 0.2 0.4 0.6 0.6
/vis/geometry/set/colour sleeve 1 0.5 0.5 0.5 0.2
/vis/geometry/set/colour cap1 1 0.5 0.5 0.5 0.2
/vis/geometry/set/colour cap2 1 0.5 0.5 0.5 0.2


# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID id
/vis/modeling/trajectories/id/default/setDrawStepPts true
/vis/modeling/trajectories/id/default/setStepPtsSize 2
/vis/modeling/trajectories/id/set e- yellow
/vis/modeling/trajectories/id/set proton red
/vis/modeling/trajectories/id/set neutron grey


# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

# Axes, scale, etc.
/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo
/vis/scene/add/logo    # 3D logo

# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)

# Make the "World" box invisible
/vis/geometry/set/visibility world 0 false

# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

